import { MemoryCapsuleItem } from '@/lib/validations/memoryCapsule';

export const DEFAULT_MEMORY_CAPSULES: MemoryCapsuleItem[] = [
  {
    id: 'CAPSULE-001',
    movieId: 'dune-2',
    movieTitle: 'דיונה: חלק שני (IMAX 3D)',
    posterUrl: 'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    date: '10/05/2026',
    timestamp: 1778371200000,
    hall: 'אולם IMAX Spatial 02',
    seats: ['F-05', 'F-06'],
    genre: 'מד״ב ואפוס',
    iconicQuote: 'הפחד הוא הורג התודעה. הפחד הוא המוות הקטן המוביל למחיקה מוחלטת.',
    characterName: 'פול אטריידיס',
    decayLevel: 0.05,
    rarityTier: 'mythic',
    hmacSignature: 'sha256-8f3e1a0b9c7d4e5f2a1b',
    reflection: {
      capsuleId: 'CAPSULE-001',
      rating: 5,
      personalNote: 'חוויה מהממת בעוצמת הסאונד של אולם האיימקס. הסצנה של רכיבת התולעת הייתה בלתי נשכחת.',
      companions: 'עם דניאל',
      favoriteScene: 'רכיבת התולעת הראשונה',
      emotionalVibe: 'עוצר נשימה',
    },
    isCustom: false,
  },
  {
    id: 'CAPSULE-002',
    movieId: 'interstellar',
    movieTitle: 'בין כוכבים: Resonated',
    posterUrl: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    date: '01/03/2026',
    timestamp: 1772496000000,
    hall: 'אולם VIP 01 - Dolby Atmos',
    seats: ['A-12', 'A-13'],
    genre: 'מד״ב ומסע בזמן',
    iconicQuote: 'אהבה היא הדבר היחיד שאנו מסוגלים לתפוס שמתעלה מעבר לממדי הזמן והחלל.',
    characterName: 'קופר',
    decayLevel: 0.2,
    rarityTier: 'legendary',
    hmacSignature: 'sha256-3c2b1a9f8e7d6c5b4a3f',
    reflection: {
      capsuleId: 'CAPSULE-002',
      rating: 5,
      personalNote: 'המוזיקה של האנס זימר בסיום פשוט גרמה לכולנו לבכות. רסיס זיכרון לנצח.',
      companions: 'משפחה',
      favoriteScene: 'סצנת העגינה בסחרור',
      emotionalVibe: 'עמוק ומרגש',
    },
    isCustom: false,
  },
  {
    id: 'CAPSULE-003',
    movieId: 'gladiator-2',
    movieTitle: 'גלדיאטור 2 - גרסת ה-VIP',
    posterUrl: 'https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg',
    date: '15/12/2025',
    timestamp: 1765756800000,
    hall: 'אולם VIP Gold Lounge',
    seats: ['E-01', 'E-02'],
    genre: 'אקשן היסטורי',
    iconicQuote: 'מה שאנחנו עושים בחיים מהדהד בנצח.',
    characterName: 'לוסיוס',
    decayLevel: 0.45,
    rarityTier: 'rare',
    hmacSignature: 'sha256-4a5b6c7d8e9f0a1b2c3d',
    reflection: {
      capsuleId: 'CAPSULE-003',
      rating: 4,
      personalNote: 'קרבות קולוסיאום מרהיבים והפופקורן כמהין היה מושלם.',
      companions: 'חברים מהעבודה',
      favoriteScene: 'קרב הזירה הימי',
      emotionalVibe: 'אדרנלין טהור',
    },
    isCustom: false,
  },
  {
    id: 'CAPSULE-004',
    movieId: 'matrix',
    movieTitle: 'המטריקס: Reborn',
    posterUrl: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
    date: '01/08/2025',
    timestamp: 1754006400000,
    hall: 'אולם 3D Haptic 05',
    seats: ['B-04'],
    genre: 'מד״ב וסייברפאנק',
    iconicQuote: 'אין כפית. זו רק התודעה שלך שמתכופפת.',
    characterName: 'ניאו',
    decayLevel: 0.75,
    rarityTier: 'rare',
    hmacSignature: 'sha256-9e8d7c6b5a4f3e2d1c0b',
    reflection: {
      capsuleId: 'CAPSULE-004',
      rating: 5,
      personalNote: 'ההקרנה במושבי הרטט הייתה כמו להיכנס לתוך המטריקס בעצמך.',
      companions: 'לבד בחצות',
      favoriteScene: 'התחמקות מכדורים על הגג',
      emotionalVibe: 'מחשמל',
    },
    isCustom: false,
  },
];
