export interface FeaturedTrailer {
  id: string;
  movieId: string;
  title: string;
  originalTitle?: string;
  trailerKey: string;
  category: string;
  rating: number;
  year: number;
  backdrop: string;
  poster: string;
}

export const FEATURED_TRAILERS: FeaturedTrailer[] = [
  {
    id: '1',
    movieId: '693134',
    title: 'חולית: חלק 2 (Dune: Part Two)',
    originalTitle: 'Dune: Part Two',
    trailerKey: 'Way9Dexny3w',
    category: 'מדע בדיוני',
    rating: 8.8,
    year: 2024,
    backdrop: 'https://image.tmdb.org/t/p/w780/eZ239CUp1d6OryZEBPnO2n87gMG.jpg',
    poster: 'https://image.tmdb.org/t/p/w500/xLMebtAGPXYCTOHY4YxXHUCQ2Rq.jpg',
  },
  {
    id: '2',
    movieId: '533535',
    title: 'דדפול & וולברין (Deadpool & Wolverine)',
    originalTitle: 'Deadpool & Wolverine',
    trailerKey: '73_1biulkYk',
    category: 'אקשן',
    rating: 8.2,
    year: 2024,
    backdrop: 'https://image.tmdb.org/t/p/w780/by8z9Fe8y7p4jo2YlW2SZDnptyT.jpg',
    poster: 'https://image.tmdb.org/t/p/w500/szdi0IOiom76a4lC4sqLkuz380l.jpg',
  },
  {
    id: '3',
    movieId: '558449',
    title: 'גלדיאטור 2 (Gladiator II)',
    originalTitle: 'Gladiator II',
    trailerKey: '4rgYUipGJNo',
    category: 'אקשן',
    rating: 8.4,
    year: 2024,
    backdrop: 'https://image.tmdb.org/t/p/w780/tOqIwliWMovSIZ9DyvHcHI7p2im.jpg',
    poster: 'https://image.tmdb.org/t/p/w500/dsopfD3XEZ1syOTll87AeL5nQWj.jpg',
  },
  {
    id: '4',
    movieId: '1022789',
    title: 'הקול בראש 2 (Inside Out 2)',
    originalTitle: 'Inside Out 2',
    trailerKey: 'LEjhY15eCx0',
    category: 'אנימציה',
    rating: 8.0,
    year: 2024,
    backdrop: 'https://image.tmdb.org/t/p/w780/p5ozvmdgsmbWe0H8Xk7Rc8SCwAB.jpg',
    poster: 'https://image.tmdb.org/t/p/w500/ivYuvwrjV0HISYdLHqfBRjzQNsA.jpg',
  },
  {
    id: '5',
    movieId: '945961',
    title: 'הנוסע השמיני: רומולוס (Alien: Romulus)',
    originalTitle: 'Alien: Romulus',
    trailerKey: 'x0XDEhP4MQs',
    category: 'אימה',
    rating: 8.1,
    year: 2024,
    backdrop: 'https://image.tmdb.org/t/p/w780/iYqSQaWDttQIQzsxg9xHyg0bttG.jpg',
    poster: 'https://image.tmdb.org/t/p/w500/vA5QqjZqaQAqvCF2SMUSQcZVHVN.jpg',
  },
  {
    id: '6',
    movieId: '889737',
    title: 'ג\'וקר: טירוף בשניים (Joker: Folie à Deux)',
    originalTitle: 'Joker: Folie à Deux',
    trailerKey: '_OKAwz2MsJs',
    category: 'דרמה',
    rating: 7.9,
    year: 2024,
    backdrop: 'https://image.tmdb.org/t/p/w780/AVWlQpVhpudyFsSh3OQIieHHYf.jpg',
    poster: 'https://image.tmdb.org/t/p/w500/z9nJQXfyzSSitQUYI5vh8krrAF.jpg',
  },
  {
    id: '7',
    movieId: '872585',
    title: 'אופנהיימר (Oppenheimer)',
    originalTitle: 'Oppenheimer',
    trailerKey: 'uYPbbksJxIg',
    category: 'דרמה',
    rating: 8.9,
    year: 2023,
    backdrop: 'https://image.tmdb.org/t/p/w780/neeNHeXjMF5fXoCJRsOmkNGC7q.jpg',
    poster: 'https://image.tmdb.org/t/p/w500/oPfQrmf2YgwSKKdaqDohtk0LciQ.jpg',
  },
  {
    id: '8',
    movieId: '786892',
    title: 'פיוריוסה: מסאגת מקס הזועם (Furiosa)',
    originalTitle: 'Furiosa: A Mad Max Saga',
    trailerKey: 'XJMuhwVlca4',
    category: 'אקשן',
    rating: 8.3,
    year: 2024,
    backdrop: 'https://image.tmdb.org/t/p/w780/raph7qjAGTMXaIjVxt6ZDSXRzUr.jpg',
    poster: 'https://image.tmdb.org/t/p/w500/tqs5m5tgwLysyok1v7y0R2Yz3aG.jpg',
  },
  {
    id: '9',
    movieId: '157336',
    title: 'בין כוכבים (Interstellar)',
    originalTitle: 'Interstellar',
    trailerKey: 'zSWdZVtXT7E',
    category: 'מדע בדיוני',
    rating: 8.9,
    year: 2014,
    backdrop: 'https://image.tmdb.org/t/p/w780/5XNQBqnBwPA9yT0jZ0p3s8bbLh0.jpg',
    poster: 'https://image.tmdb.org/t/p/w500/9W7qYnmi1W3648YXVJvpjk82MUf.jpg',
  },
  {
    id: '10',
    movieId: '569094',
    title: 'ספיידרמן: מעבר לממדי העכביש',
    originalTitle: 'Spider-Man: Across the Spider-Verse',
    trailerKey: 'cqGjhVJWtEg',
    category: 'אנימציה',
    rating: 8.7,
    year: 2023,
    backdrop: 'https://image.tmdb.org/t/p/w780/kVd3a9YeLGkoeR50jGEXM6EqseS.jpg',
    poster: 'https://image.tmdb.org/t/p/w500/78WGOACqLbhR93YfMLSBSIP2pIF.jpg',
  },
  {
    id: '11',
    movieId: '414906',
    title: 'באטמן (The Batman)',
    originalTitle: 'The Batman',
    trailerKey: 'mqqft2x_Aa4',
    category: 'אקשן',
    rating: 8.5,
    year: 2022,
    backdrop: 'https://image.tmdb.org/t/p/w780/IYUD7rAIXzBM91TT3Z5fILUS7n.jpg',
    poster: 'https://image.tmdb.org/t/p/w500/bIM9IhCzprl0lBr4XrETVCYYfmL.jpg',
  },
  {
    id: '12',
    movieId: '1241982',
    title: 'מואנה 2 (Moana 2)',
    originalTitle: 'Moana 2',
    trailerKey: 'hDZ7y8RP5HE',
    category: 'אנימציה',
    rating: 7.8,
    year: 2024,
    backdrop: 'https://image.tmdb.org/t/p/w780/vYqt6kb4lcF8wwqsMMaULkP9OEn.jpg',
    poster: 'https://image.tmdb.org/t/p/w500/x7jLMI3EPYh8WEcpYjtwpwcDahQ.jpg',
  },
  {
    id: '13',
    movieId: '76600',
    title: 'אווטאר: דרכם של המים',
    originalTitle: 'Avatar: The Way of Water',
    trailerKey: 'd9MyW72ELq0',
    category: 'מדע בדיוני',
    rating: 8.6,
    year: 2022,
    backdrop: 'https://image.tmdb.org/t/p/w780/kJsPVzdyBrYHLomuNv5SJDXUQ2f.jpg',
    poster: 'https://image.tmdb.org/t/p/w500/cnfhtzcvYxoG5Mm2X84HfCV5sle.jpg',
  },
  {
    id: '14',
    movieId: '402431',
    title: 'מרשעת (Wicked)',
    originalTitle: 'Wicked',
    trailerKey: '6COmYeLsz4c',
    category: 'דרמה',
    rating: 8.1,
    year: 2024,
    backdrop: 'https://image.tmdb.org/t/p/w780/fyZ6SDUS4o9jp2EHxfZa3qS9ean.jpg',
    poster: 'https://image.tmdb.org/t/p/w500/6o7fhIHEGJ8lyR5v87Df1CFpMOQ.jpg',
  },
];
